name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15.6
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.6'
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  assets:
    needs: build
    name: Upload Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - run: aws --version
      - name: Set up Go 1.15.6
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
      - name: Install ulid Commandline Tool
        run: go get -v github.com/oklog/ulid/v2/cmd/ulid
      - name: Upload
        run: |
          sudo sh -c 'curl -s "http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=co" > /etc/mime.types'
          export S3_PREFIX="assets/$(ulid)"
          aws s3 sync ./web/static/ s3://$ASSETS_S3_BUCKET_NAME/$S3_PREFIX --cache-control 'max-age=31536000' --acl public-read
          mkdir ci
          echo "assets_url: \"https://$ASSETS_S3_BUCKET_DOMAIN_NAME\"" >> ./ci/config.yaml
          echo "assets_prefix: \"$S3_PREFIX\"" >> ./ci/config.yaml
          cat ./ci/config.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.ASSETS_AWS_REGION }}
          ASSETS_S3_BUCKET_NAME: ${{ secrets.ASSETS_S3_BUCKET_NAME }}
          ASSETS_S3_BUCKET_DOMAIN_NAME: ${{ secrets.ASSETS_S3_BUCKET_DOMAIN_NAME }}
      - name: Upload CI config.yml for Assets
        uses: actions/upload-artifact@v2
        with:
          name: ci-config
          path: ./ci/config.yaml

  docker:
    needs: assets
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: tugberk/tugberk-go-bloggy # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag
      - name: Download ci-config Artifact
        uses: actions/download-artifact@v2
        with:
          name: ci-config
          path: ./ci/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-web.dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true