name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15.6
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.6'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  assets:
    needs: build
    name: Upload Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - run: aws --version
      - name: Set up Go 1.15.6
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
      - name: Install ulid Commandline Tool
        run: go get -v github.com/oklog/ulid/v2/cmd/ulid
      - name: Upload
        run: |
          cat /etc/mime.types
          curl -s "http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=co" > ~/.mime.types
          export S3_PREFIX="assets/$(ulid)"
          aws s3 sync ./web/static/ s3://$ASSETS_S3_BUCKET_NAME/$S3_PREFIX --cache-control 'max-age=31536000' --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.ASSETS_AWS_REGION }}
          ASSETS_S3_BUCKET_NAME: ${{ secrets.ASSETS_S3_BUCKET_NAME }}
          ASSETS_S3_BUCKET_DOMAIN_NAME: ${{ secrets.ASSETS_S3_BUCKET_DOMAIN_NAME }}