name: Stale

on:
  pull_request:
    branches: [ master ]
    
jobs:
  stale:
    runs-on: ubuntu-latest
    name: Stale-Check
    steps:
    - name: Close Stale Issues
      uses: actions/stale@v8.0.0
            
